typography_spectrum: 0.9924416658492519
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.4139594588722886
  lightness: 0.34010550280083157
  saturation: 0.11600116847931306
  rhythmicContrast: 0.1991554076908765
github: true
layout_spectrum: 0.3130356325453498
author:
  name: Freddy Macrez
  url: 'https://thegrid.ai/freddy-macrez/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1fa71872-086b-46f4-90a1-93ccc4c4f59b.png
name: freddy macrez
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Essaie
    id: c6ee9faf-7f36-4a27-a63c-352dc9eaa6eb
    type: content
  - name: Gagnez
    id: 445f5cc2-5f05-47b0-9390-05cd22c9ec68
    type: content
  - name: FaceBook
    url: 'https://www.facebook.com/MACREZFREDDY'
    type: external
  - name: Jeu
    url: >-
      https://www.esn-lejeu.com/?utm_source=facebook&utm_campaign=M-1865-mob&utm_medium=cpc
    type: external
  - name: Ciel
    url: >-
      https://www.google.fr/search?q=ciel+etoile&client=ubuntu&hs=TI&tbm=isch&source=lnt&tbs=sur:fc&sa=X&ved=0ahUKEwjmotP-iPnaAhXG0RQKHXGbAf8QpwUIHg&biw=1375&bih=785&dpr=1#imgrc=qikoxr16kICuFM:
    type: external
  - name: Blog
    url: 'https://blog.thegrid.io/'
    type: external
  - name: 'commandements '
    id: 96eb7f57-5e3d-4af2-ae1b-29e9f3a47797
    type: content
favicon: null
title: Freddy Macrez
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/da64502f-6596-4566-96ff-9d2133936689.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/da64502f-6596-4566-96ff-9d2133936689.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Essai de Molly, l''intelligence artificielle qui con√ßoit votre site web.'
