layout_spectrum: 0.3189354409863896
typography_spectrum: 0.9943461369765498
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.4403218273586123
  lightness: 0.11866187274880191
  saturation: 0.5387500825445952
  rhythmicContrast: 0.026984099312362696
github: true
author:
  name: Freddy Macrez
  url: 'https://thegrid.ai/freddy-macrez/'
  email: creafred.informatique@gmail.com
logo: null
name: freddy macrez
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Accueil
    id: c6ee9faf-7f36-4a27-a63c-352dc9eaa6eb
    type: content
  - name: Technologies
    id: 445f5cc2-5f05-47b0-9390-05cd22c9ec68
    type: content
  - name: Jeu
    url: >-
      https://www.esn-lejeu.com/?utm_source=facebook&utm_campaign=M-1865-mob&utm_medium=cpc
    type: external
  - name: Lien
    id: a64a19cb-8224-4fd9-9d2d-383bb28339c7
    type: content
favicon: null
title: Freddy Macrez
content: []
description: 'Blog   '
